# Generated by Django 5.2.1 on 2025-05-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('company', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('exist', models.CharField(max_length=3)),
            ],
        ),
    ]
